[Container]

# Dynamic Environment Variables
# Auth
Environment=URLS_SELF_ISSUER=https://%H/
Environment=URLS_SELF_PUBLIC=https://%H/
Environment=URLS_LOGIN=https://%H/login
Environment=URLS_CONSENT=https://%H/consent
Environment=URLS_LOGOUT=https://%H/logout

# Boot
Environment=BSS_IPXE_SERVER=%H
