#!/bin/bash

update_dns() {
    local system_fqdn=$1
    local short_name="${system_fqdn%%.*}" 
    local dns_name="${system_fqdn#*.}"
    local primary_ip=$(hostname -I | awk '{print $1}')
    
    # Update names in environment and acme containers
    sed -i "s/^SYSTEM_NAME=.*/SYSTEM_NAME=${short_name}/" /etc/openchami/configs/openchami.env
    sed -i "s/^SYSTEM_DOMAIN=.*/SYSTEM_DOMAIN=${dns_name}/" /etc/openchami/configs/openchami.env
    sed -i "s/^SYSTEM_URL=.*/SYSTEM_URL=${system_fqdn}/" /etc/openchami/configs/openchami.env
    sed -i "s|^URLS_SELF_ISSUER=.*|URLS_SELF_ISSUER=https://${system_fqdn}|" /etc/openchami/configs/openchami.env
    sed -i "s|^URLS_SELF_PUBLIC=.*|URLS_SELF_PUBLIC=https://${system_fqdn}|" /etc/openchami/configs/openchami.env
    sed -i "s|^URLS_LOGIN=.*|URLS_LOGIN=https://${system_fqdn}/login|" /etc/openchami/configs/openchami.env
    sed -i "s|^URLS_CONSENT=.*|URLS_CONSENT=https://${system_fqdn}/consent|" /etc/openchami/configs/openchami.env
    sed -i "s|^URLS_LOGOUT=.*|URLS_LOGOUT=https://${system_fqdn}/logout|" /etc/openchami/configs/openchami.env
    sed -i "s|-d .* \\\\|-d ${system_fqdn} \\\\|" /usr/share/containers/systemd/acme-deploy.container
    sed -i "s/^ContainerName=.*/ContainerName=${system_fqdn}/" /usr/share/containers/systemd/acme-register.container
    sed -i "s/^HostName=.*/HostName=${system_fqdn}/" /usr/share/containers/systemd/acme-register.container
    sed -i "s|-d .* \\\\|-d ${system_fqdn} \\\\|" /usr/share/containers/systemd/acme-register.container
    sed -i "s|--add-host='.*|--add-host='${system_fqdn}:${primary_ip}'|" /usr/share/containers/systemd/opaal.container

    # Reload systemD after .container changes
    systemctl daemon-reload

    echo "Changed FQDN to ${1}"
    echo 'Either restart all of the OpenCHAMI services:'
    echo
    echo '  sudo systemctl restart openchami.target'
    echo
    echo 'or run the following to just regenerate/redeploy the certificates:'
    echo
    echo '  sudo systemctl restart acme-deploy'
    echo
}

help_page() {
    echo "OpenCHAMI Certificate Update"
    echo "Update OpenCHAMI Certificates"
    echo "Usage: $0 update FQDN"
    echo
    echo "EXAMPLES:"
    echo "  $0 update demo.openchami.cluster"

}
case "$1" in 
    update)
        if [[ -z "$2" ]]; then
            help_page
        else
            if [[ $EUID -ne 0 ]]; then
                echo "This script must be run as root" 
                exit 1
            else
                update_dns "$2"
            fi
        fi
        ;;
    *)
        help_page
        exit 1
    ;;
esac