#!/bin/bash

update_dns() {
    local system_fqdn=$1
    mkdir -v -p /etc/containers/systemd/containers.d

    echo "Updating local site-specific OpenCHAMI URL overrides..."
    cat <<EOF | tee /etc/containers/systemd/containers.d/99-openchami-site-override.conf
    # MANAGED BY '${0}'
    [Container]
    Environment=URLS_SELF_ISSUER=https://${system_fqdn}
    Environment=URLS_SELF_PUBLIC=https://${system_fqdn}
    Environment=URLS_LOGIN=https://${system_fqdn}/login
    Environment=URLS_CONSENT=https://${system_fqdn}/consent
    Environment=URLS_LOGOUT=https://${system_fqdn}/logout
EOF

    echo "Updating local site-specific OpenCHAMI ACME FQDN..."
    mkdir -v -p  /etc/containers/systemd/acme-deploy.service.d
    cat <<EOF | tee /etc/containers/systemd/acme-deploy.service.d/99-site-override.conf
    # MANAGED BY '$0'
    [Container]
    Environment=SYSTEM_FQDN=${system_fqdn}
EOF


    mkdir -v -p  /etc/containers/systemd/acme-register.service.d
    cat <<EOF | tee /etc/containers/systemd/acme-register.service.d/99-site-override.conf
    # MANAGED BY '${0}'
    [Container]
    ContainerName=${system_fqdn}
    HostName=${system_fqdn}
    Environment=SYSTEM_FQDN=${system_fqdn}
EOF

    # Reload systemD after .container changes
    systemctl daemon-reload

    echo "Changed FQDN to ${1}"
    echo 'Either restart all of the OpenCHAMI services:'
    echo
    echo '  sudo systemctl restart openchami.target'
    echo
    echo 'or run the following to just regenerate/redeploy the certificates:'
    echo
    echo '  sudo systemctl restart acme-deploy'
    echo
}

help_page() {
    echo "OpenCHAMI Certificate Update"
    echo "Update OpenCHAMI Certificates"
    echo "Usage: $0 update FQDN"
    echo
    echo "EXAMPLES:"
    echo "  $0 update demo.openchami.cluster"

}
case "$1" in 
    update)
        if [[ -z "$2" ]]; then
            help_page
        else
            if [[ $EUID -ne 0 ]]; then
                echo "This script must be run as root" 
                exit 1
            else
                update_dns "$2"
            fi
        fi
        ;;
    *)
        help_page
        exit 1
    ;;
esac